baseurl = "https://docs.logit.io/"
languageCode = "en-gb"
title = "Logit Docs"
theme = "hugo-logit-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-48517318-1"

[params]
	# General information
	author = "Logit"
	description = "Documentation for hosted ELK provided by logit.io"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub2"
	repo_url = "https://github.com/logit-io/hugo"

	version = "0.0.1"
	#logo = "favicon.ico"
	favicon = "favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["logit.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		primary = "green"
		accent  = "light green"

	[params.font]
		text = "Lato"
		code = "Lato"

[social]
	twitter = "logit_io"
	github  = "logit-io"




[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
